SELECT CC.CHAN_EMAIL_PRIORITY, CC.CHAN_IVR_PRIORITY, CC.CHAN_SMS_PRIORITY,
  CC.CHAN_SECURE_PRIORITY, CC.CHAN_MAIL_PRIORITY, CC.CHAN_DEFAULT,
  CC.REQUIRED, CC.MANDATORY, PC.CHAN_EMAIL_PRIORITY, PC.CHAN_IVR_PRIORITY,
  PC.CHAN_SMS_PRIORITY, PC.CHAN_SECURE_PRIORITY, PC.CHAN_DEFAULT,
  PC.REQUIRED, PC.MANDATORY, P.NAME, P.DESCRIPTION
  FROM CLIENT_CONFIGURATION AS CC, PROGRAM_CONFIGURATION AS PC, PROGRAM AS P,
       PROGRAM_PROFILE_CLIENT_EXCEPTION AS PPCE
  WHERE CC.CLIENT_ID = 142 AND CC.COMMUNICATION_ID = 261
    AND PC.COMMUNICATION_ID = CC.COMMUNICATION_ID AND PC.PROGRAM_ID = P.ID
    AND PPCE.CLIENT_ID = CC.CLIENT_ID AND PPCE.PROGRAM_ID = P.ID
