SELECT P.ID, P.NAME, P.DESCRIPTION, PP.DISPLAY_ORDER, PP.DEFAULT_OPT_IN,
  PP.VISIBLE_IN_UI, PP.CHAN_EMAIL, PP.CHAN_IVR, PP.CHAN_SMS, PP.CHAN_SECURE,
  PC.CHAN_EMAIL_PRIORITY, PC.CHAN_IVR_PRIORITY, PC.CHAN_SMS_PRIORITY,
  PC.CHAN_SECURE_PRIORITY, PC.CHAN_DEFAULT, PC.REQUIRED, PC.MANDATORY
  FROM PROGRAM AS P, PROGRAM_PROFILE AS PP, PROGRAM_CONFIGURATION AS PC
  WHERE PC.COMMUNICATION_ID = 261 AND P.ID = PP.PROGRAM_ID AND PC.PROGRAM_ID = P.ID
    AND (PP.EFFECTIVE <= CURRENT_TIMESTAMP AND PP.EXPIRATION >= CURRENT_TIMESTAMP)
    AND (PC.EFFECTIVE <= CURRENT_TIMESTAMP AND PC.EXPIRATION >= CURRENT_TIMESTAMP)
