SELECT PROG.ID, PROG.NAME, PROG.DESCRIPTION, 
  PROG_PROF.DISPLAY_ORDER,
  COALESCE( PROG_PROF_CLT.VISIBLE_IN_UI, PROG_PROF.VISIBLE_IN_UI) AS VISIBLE_IN_UI,
  COALESCE( PROG_PROF_CLT.CHAN_EMAIL,    PROG_PROF.CHAN_EMAIL)    AS CHAN_EMAIL,
  COALESCE( PROG_PROF_CLT.CHAN_IVR,      PROG_PROF.CHAN_IVR)      AS CHAN_IVR,
  COALESCE( PROG_PROF_CLT.CHAN_SMS,      PROG_PROF.CHAN_SMS)      AS CHAN_SMS,
  COALESCE( PROG_PROF_CLT.CHAN_SECURE,   PROG_PROF.CHAN_SECURE)   AS CHAN_SECURE,
  CASE 
  	WHEN PROG_PROF_CLT.ID IS NULL THEN 'STANDARD'
  	WHEN PROG_PROF_CLT.ID IS NOT NULL THEN 'CLIENT'
  END AS PROGRAM_RULE
FROM
  PROGRAM AS PROG 
    JOIN PROGRAM_PROFILE AS PROG_PROF ON PROG.ID = PROG_PROF.PROGRAM_ID 
      LEFT OUTER JOIN PROGRAM_PROFILE_CLIENT_EXCEPTION AS PROG_PROF_CLT 
        ON PROG.ID = PROG_PROF_CLT.PROGRAM_ID AND PROG_PROF_CLT.CLIENT_ID = :CLIENT_ID
WHERE (PROG_PROF.EFFECTIVE <= CURRENT_TIMESTAMP AND PROG_PROF.EXPIRATION > CURRENT_TIMESTAMP)
  AND (PROG_PROF_CLT.ID IS NULL OR (PROG_PROF_CLT.EFFECTIVE <= CURRENT_TIMESTAMP AND PROG_PROF_CLT.EXPIRATION > CURRENT_TIMESTAMP));
   
