--<ScriptOptions statementTerminator=";"/>

ALTER TABLE "DB2ADMIN"."PROGRAM" DROP CONSTRAINT "SQL180122194343880";

DROP TABLE "DB2ADMIN"."PROGRAM";

CREATE TABLE "DB2ADMIN"."PROGRAM" (
		"ID" INTEGER NOT NULL, 
		"DESCRIPTION" VARCHAR(255 OCTETS), 
		"NAME" VARCHAR(255 OCTETS), 
		"HOUSE_KPG_CREATE_TIME" TIMESTAMP, 
		"HOUSE_KPG_CREATE_TRAN_CD" INTEGER NOT NULL, 
		"HOUSE_KPG_CREATE_USER" VARCHAR(255 OCTETS), 
		"HOUSE_KPG_UPDATE_TIME" TIMESTAMP, 
		"HOUSE_KPG_UPDATE_TRAN_CD" INTEGER NOT NULL, 
		"HOUSE_KPG_UPDATE_USER" VARCHAR(255 OCTETS)
	)
	ORGANIZE BY ROW
	DATA CAPTURE NONE 
	IN "USERSPACE1"
	COMPRESS NO;

ALTER TABLE "DB2ADMIN"."PROGRAM" ADD CONSTRAINT "SQL180122194343880" PRIMARY KEY
	("ID");

