-- <ScriptOptions statementTerminator=";" />
DROP TABLE ECCM.TMCN_CMM_CHL_SBI;
CREATE TABLE ECCM.TMCN_CMM_CHL_SBI ( -- Member Communication Channel Subscription
    MCN_BNF_ID INTEGER NOT NULL,
    MCN_SEQ_NB SMALLINT NOT NULL,
    MCN_EFF_DT DATE NOT NULL,
    MCN_EXP_DT DATE NOT NULL,
    MCN_CLT_ID INTEGER NULL,
    MCN_EMA_SBI_CD SMALLINT NULL,
    MCN_EMA_SBI_EMA_TX VARCHAR(254) NULL,
    MCN_TX_SBI_CD SMALLINT NULL,
    MCN_TX_SBI_PHE_TX VARCHAR(10) NULL,
    MCN_CLR_SBI_CD SMALLINT NULL,
    MCN_CLR_SBI_PHE_TX VARCHAR(10) NULL,
    MCN_HSC_TRN_CD SMALLINT NOT NULL,
    MCN_HSC_SRC_CD SMALLINT NOT NULL,
    MCN_HSC_USR_ID CHAR(8) NOT NULL,
    MCN_HSC_TS TIMESTAMP NOT NULL,
    MCN_HSU_TRN_CD SMALLINT NOT NULL,
    MCN_HSU_SRC_CD SMALLINT NOT NULL,
    MCN_HSU_USR_ID CHAR(8) NOT NULL,
    MCN_HSU_TS TIMESTAMP NOT NULL,
    PRIMARY KEY ( MCN_BNF_ID, MCN_SEQ_NB ) );

DELETE FROM ECCM.TMCN_CMM_CHL_SBI;
INSERT INTO ECCM.TMCN_CMM_CHL_SBI (
    MCN_BNF_ID, MCN_SEQ_NB, MCN_EFF_DT, MCN_EXP_DT, MCN_CLT_ID,
    MCN_EMA_SBI_CD, MCN_EMA_SBI_EMA_TX, MCN_TX_SBI_CD, MCN_TX_SBI_PHE_TX, MCN_CLR_SBI_CD, MCN_CLR_SBI_PHE_TX,
    MCN_HSC_TRN_CD, MCN_HSC_SRC_CD, MCN_HSC_USR_ID, MCN_HSC_TS, MCN_HSU_TRN_CD, MCN_HSU_SRC_CD, MCN_HSU_USR_ID, MCN_HSU_TS )
  VALUES 
  ( 123456789, 1, '2017-01-01', '9999-12-31', 12345, 
    1, 'user@domain.tld', 1, '1234567890', 1, '1234567890',  
    0, 0, 'QCPI24K', CURRENT_TIMESTAMP, 0, 0, 'QCPI24K', CURRENT_TIMESTAMP);
    
SELECT * FROM ECCM.TMCN_CMM_CHL_SBI; 
    